export { default as ArrowDown } from "./ArrowDown";
export { default as Bag } from "./Bag";
export { default as Facebook } from "./Facebook";
export { default as Glia } from "./Glia";
export { default as Instagram } from "./Instagram";
export { default as Twitter } from "./Twitter";
export { default as User } from "./User";
export { default as Wishlist } from "./Wishlist";
export { default as Youtube } from "./Youtube";
